### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by tokejepsen** [tokejepsen/pyblish-deadline#1]
### Goal

To make a universal Deadline package for Pyblish, that can work for all pipelines with minimal configuration.

##### Selection
We gather all the necessary instances from the work file, like renderlayers in Maya or write nodes in Nuke.

##### Validation
I'm not entirely sure what data to validate at the moment, but initial thoughts could be to validate the existence of output paths.

##### Extraction
We extract the deadline data to the job and plugin file, which are just text files. These go to a temporary location, ready for conforming.

##### Conform
The conform plugin picks up the the job and plugin files, and relocates them to the final destination of the renders. The plugin also modifies the output directories in the job file and the scene file in the plugin file, according to a configuration file outside of the plugin.
The configuration file structure I have yet to figure out exact details of, but it would be a config file that doesn't get recognized by git and can be modified per pipeline.
Finally the conform plugin submits the job to deadline.

**Comment by mottosso** [comment]
Besides a file, what other data is essential for Deadline to perform a render, and what data is optional but useful?

**Comment by tokejepsen** [comment]
> Besides a file, what other data is essential for Deadline to perform a render, and what data is optional but useful?

To submit a job to Deadline you need the job file, and the plugin file. All data that Deadline needs are included in these files.

#### Example
##### Job File
```
Name=tcu_008_030.light.v003 - tcu_008_030_camera_anim_v001:camera
UserName=toke.jepsen
Frames=1-254
Group=maya_2015
Pool=medium
LimitGroups=arnold
Blacklist=
ScheduledStartDateTime=31/03/2015 11:14
MachineName=061-KUVIRA-PC
Plugin=MayaBatch
OutputDirectory0=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\ao_layer
OutputDirectory1=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\masterLayer
OutputDirectory2=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\floor_layer
OutputDirectory3=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\led_layer
OutputDirectory4=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\tech_layer
OutputDirectory5=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\ao_layer
OutputDirectory6=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\masterLayer
OutputDirectory7=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\floor_layer
OutputDirectory8=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\led_layer
OutputDirectory9=Y:\projects\the_call_up_00897\sequences\tcu_008\tcu_008_030\lighting\output\tech_layer
OutputFilename0=tcu_008_030.light.v003.####.exr
OutputFilename1=tcu_008_030.light.v003.####.exr
OutputFilename2=tcu_008_030.light.v003.####.exr
OutputFilename3=tcu_008_030.light.v003.####.exr
OutputFilename4=tcu_008_030.light.v003.####.exr
OutputFilename5=tcu_008_030.light.v003.####.exr
OutputFilename6=tcu_008_030.light.v003.####.exr
OutputFilename7=tcu_008_030.light.v003.####.exr
OutputFilename8=tcu_008_030.light.v003.####.exr
OutputFilename9=tcu_008_030.light.v003.####.exr
```
##### Plugin File
```
Animation=1
Renderer=arnold
UsingRenderLayers=1
RenderLayer=
RenderHalfFrames=0
FrameNumberOffset=0
LocalRendering=0
StrictErrorChecking=1
MaxProcessors=0
ArnoldVerbose=1
Version=2015
Build=64bit
ProjectPath=Y:/projects/the_call_up_00897/sequences/tcu_008/tcu_008_030/lighting
StartupScript=
ImageWidth=2048
ImageHeight=1152
OutputFilePath=Y:/projects/the_call_up_00897/sequences/tcu_008/tcu_008_030/lighting/output/
OutputFilePrefix=
Camera=tcu_008_030_camera_anim_v001:camera
Camera0=
Camera1=front
Camera2=persp
Camera3=side
Camera4=tcu_008_030_camera_anim_v001:camera
Camera5=top
SceneFile=Y:/projects/the_call_up_00897/sequences/tcu_008/tcu_008_030/lighting/tcu_008_030.light.v003.mb
IgnoreError211=0
```

**Comment by tokejepsen** [comment]
Looking at the data we will need to have more than just the output directories and scene file in the configuration file. So initially I can see that we need;

- Group
- Pool
- LimitGroups

**Comment by mottosso** [comment]
Is all of that *required* for rendering? I'm thinking it could be a good idea to make the base implementation as minimal as possible, and to allow for options to be added if needed.

For example, an output path is probably required, but specifying `front`, `side` and `top` cameras might not be?

**Comment by tokejepsen** [comment]
For tracking data for FTrack and Shotgun we could initially look at injecting it at the extraction stage, and hopefully in the future we can find a solution that can decouple FTrack/Shotgun packages from this package.

**Comment by tokejepsen** [comment]
> For example, an output path is probably required, but specifying front, side and top cameras might not be?

Yeah, the example might not have been the best. We don't need the camera or a lot of the example text. The implementation will definitely be as minimal as possible.

**Comment by mottosso** [comment]
Cool, let's have a look at what data is required.

**Required**

```yaml
# key: example
file: c:\myfile.mb
outputPath: c:\output\myfile.%03d.exr
```

**Optional**

```yaml
# key: default
camera: persp
```

What else?

**Comment by tokejepsen** [comment]
Required
```yaml
# key: example
file: c:\myfile.mb
outputPath: c:\output # name of the file comes from the extraction
```

Optional
```yaml
# key: default
# Leaving these blank will result not add them to the job file,
# resulting in a default "None" flag assigned in Deadline
pool:
group:
limitgroups:
```

**Comment by mottosso** [comment]
> outputPath: c:\output # name of the file comes from the extraction

Could this path come from any extractor, or does it need to be Deadline-specific?

I'm thinking we could let the documentation specify into what data-member an extractor must store the outputted file for the Deadline conformer to pick it up.

E.g.

> The publish will be submitted to Deadline if an instance contains the member `deadlineInput` and `deadlineOutput`, both of which are absolute paths, e.g. `c:\myfile.mb` and `c:\output\`

What you would need to implement, by the looks of it, is a Selector that gathers the optional information, and a Conformer that uses the information to communicate with Deadline.

How does one reach Deadline? Is it running at a specific ip:port combination?

**Comment by tokejepsen** [comment]
> Could this path come from any extractor, or does it need to be Deadline-specific?
I'm thinking we could let the documentation specify into what data-member an extractor must store the outputted file for the Deadline conformer to pick it up.

I guess it could come from any extractor, if the conformer looks at a specific data-member. What are you thinking this would achieve?

> How does one reach Deadline? Is it running at a specific ip:port combination?

I have been using the "deadlinecommand" executable that gets installed on all machines. This is also how Deadline seem to submitting their jobs. This; https://github.com/Bumpybox/pyblish-bumpybox/blob/master/pyblish_bumpybox/plugins/extract_deadline_data.py is a copy of the submission script Deadline uses.

**Comment by mottosso** [comment]
> I guess it could come from any extractor, if the conformer looks at a specific data-member. What are you thinking this would achieve?

Well it sounds Deadline should be capable of rendering any file, regardless of where it came from or what format it is in, and not only files specifically designed to be rendered through Deadline.

I'm thinking it might be possible to make the base implementation generic enough such that you wouldn't need to know too much about Deadline to publish to it. And then offer options for customising that further. As a user, I'm thinking all that really matters is getting the frames rendered to where you told them to go.

> I have been using the "deadlinecommand" executable that gets installed on all machines.

Ah, that's perfect.

**Comment by tokejepsen** [comment]
> I'm thinking it might be possible to make the base implementation generic enough such that you wouldn't need to know too much about Deadline to publish to it. And then offer options for customising that further. As a user, I'm thinking all that really matters is getting the frames rendered to where you told them to go.

You possibly could do something like this, and there is the commandline plugin for Deadline. But I would stick to what I know to begin with, and that is to submit job and plugin files modified to which host plugin Deadline should use. Using the built-in host plugins in Deadline also comes with tons of customization in Deadline which I use, and I know studios customize to their needs.

**Comment by mottosso** [comment]
Cool, I like it!

**Comment by tokejepsen** [comment]
##### Configuration

The choice is between yaml and json for data storage, where json being built-in to python seems like the best choice even though yaml readability might be better.

The biggest challenge is how to point to the source file and directories on disk. The paths need to support relative, and more absolute paths that can go across drives.

**Comment by mottosso** [comment]
What data storage?

This is how I understand it so far.

1. A host must generate two files; a `jobFile` and `pluginFile`
2. A host pass these files to the `deadlinecommand` executable
3. Deadline performs the job as specified by the two files.

Is that right?

**Comment by tokejepsen** [comment]
> What data storage?

Its for the conforming process, where we need a config file that people can customize for their pipeline. This would contain the required data below;

```yaml
# key: example
file: c:\myfile.mb
outputPath: c:\output # name of the file comes from the extraction
```

Where the source file is, and where to output the rendered files. Its this config file that will be storage on disk next to the conform plugin.

**Comment by mottosso** [comment]
Ah, okay. How about using plug-ins as means of customising?

For example.

**Studio plug-in**

```python
class SelectRenderLayers(...):
  def process_context(self, context):
    for layer in cmds.ls(type="renderLayer"):
      instance = context.create_instance(name=layer)
      instance.set_data("family", "pyblish-deadline.layer")

      for attr in cmds.listAttr(layer, userDefined=True):
        # This is where `outputPath` comes from, created and controlled via
        # e.g. the user or pre-defined if layer is created via a script etc.
        instance.set_data(attr, cmds.getAttr(layer + "." + attr)
```

**Pyblish for Deadline Plug-in**

```python
class ConformToDeadline(...):
  def process_instance(self, instance):
    if not instance.has_attr("outputPath"):
      return self.log.info("Nothing to do..")

    return_value = subprocess.call(["deadlinecommand"], kwargs={
      "file": instance.context.data("currentFile"),
      "renderLayer": instance.data("name"),
      "outputPath": instance.data("outputPath")
    }

    self.log.info(return_value)
```

This way, the user have control over non-Deadline specifics, like input and output files, and can pass any additional data to Deadline via user-defined attributes on the render Layer itself.

**Comment by tokejepsen** [comment]
> How about using plug-ins as means of customising?

That's a good idea. Dont know how convenient it is from a pipeline management point of view. I would expect who ever wants this customized, would be using Pyblish plugins to extract/conform to their pipeline.
So if they want the source file to be ```./publish/[source file without extension]``` relative to the work file, then they would have to setup all renderlayers on a project to this. That said though there is definitely a route to take with plugins instead of config files. Just dont know what it is yet:)

**Comment by mottosso** [comment]
> I would expect who ever wants this customized, would be using Pyblish plugins to extract/conform to their pipeline.

For a Pyblish package, I think this a safe assumption to make.

> So if they want the source file to be ./publish/[source file without extension] relative to the work file, then they would have to setup all renderlayers on a project to this. That said though there is definitely a route to take with plugins instead of config files. Just dont know what it is yet:)

I'm probably not following the way towards submitting a render yet, so bear with me :) Here's the workflow I'm picturing so far.

1. User sets up his scene, as he would regardless of Pyblish, with render layers.
2. User hits Publish, and your plug-ins take care of the rest.

By default, the output path would be wherever Maya typically stored images, e.g. the `\images` directory of the current project. If a render layer is found to have a user-defined attribute, `outputPath`, a string-attribute, containing an absolute path, it would instead render to there.

![untitled](https://cloud.githubusercontent.com/assets/2152766/7441849/85781132-f0f1-11e4-8607-8b095582e78b.gif)

That way, 

1. a new user could install your Pyblish for Deadline kit and start submitting renders right out of the box
2. and advanced users could customise things live, in Maya
3. whereas the TD overseeing the pipeline could develop tools that help artists create and manage these overriding attribute on their render layers.

Here's some more along these lines of thinking.

- https://github.com/pyblish/pyblish/issues/116

Thoughts?

**Comment by tokejepsen** [comment]
> a new user could install your Pyblish for Deadline kit and start submitting renders right out of the box
and advanced users could customise things live, in Maya

I think this is a good work flow, and I'd like this functionality available.

> whereas the TD overseeing the pipeline could develop tools that help artists create and manage these overriding attribute on their render layers.

This where I would like the TD to be able to customize the paths with plugins rather than making costum tools "outside" of Pyblish.
The best solution would to have a plugin that the TD "slots in" somewhere to customize the paths. Just dont know where and how that would work.

**Comment by mottosso** [comment]
> The best solution would to have a plugin that the TD "slots in" somewhere to customize the paths. Just dont know where and how that would work.

How about something like this?

```python
import pyblish_deadline
pyblish_deadline.register_configuration_file(r"\\custom\path\deadline_config.json")

# Or
import os
os.environ["PYBLISH_DEADLINE_CONFIGURATION_FILE"] = r"\\custom\path\deadline_config.json"
```

Then I'm not sure exactly what sort of configuration you need. I would think the final paths to be dependent on the specific scene and render layer being worked on. In that case, you could template it.

**deadline_config.json**

```json
{
  "outputPath": "\\\\server\\{project}\\published\\{sceneName}\\{renderLayer}.###.{format}"
}
```

From there, you can read and format it like this.

```python
import json

# Studio module
import pipeline

config = ""
with open("\\server\..json") as f:
  config = json.load(f)
  config["outputPath"] = config["outputPath"].format(
    # Feed it data from pipeline modules, context and instances
    project=pipeline.current_project(),
    sceneName=instance.context.data("currentFile"),
    renderLayer=instance.data("name"),
    format=instance.data("format"))

# outputs
{"outputPath": "\\server\MyProject\published\shot001_marcus_v001\beauty.###.exr"}
```

**Comment by tokejepsen** [comment]
What do you think of this?

I offset the deadline conformer to evaluate after the default conformer order. TDs can make a conformer that will inject a "deadlineFile" (source file) and "deadlinePath" (output path) into the context?
Thinking it easier to get the necessary data in a Pyblish session, with Ftrack/Shotgun data usually easily available.

**Comment by mottosso** [comment]
Yeah, sounds like a good idea. Except I would expect a Selector to be injecting this data.

"file" and "path" sounds too similar imo, I would go for something involving "input" and "output". E.g inputPath and outputPath.

**Comment by tokejepsen** [comment]
> Except I would expect a Selector to be injecting this data.
"file" and "path" sounds too similar imo, I would go for something involving "input" and "output". E.g inputPath and outputPath.

Sounds good to me:) Think I'm ready to get going.

**Comment by tokejepsen** [comment]
got an initial implementation, so closing this

**Comment by mottosso** [comment]
Would you like to get it into the main Pyblish account? Since this isn't a fork, and it doesn't exist there yet, we should be able to transfer it. From there, you could fork it back to your account as usual and continue working.

Just have a look to make sure it's ok with the [guidelines](https://github.com/pyblish/pyblish/wiki/Writing-Extensions).
